# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

test:  
  override:
    - "true"
    
deployment:
  production:
    branch: master
    commands:
      - scp -r * your-username@your-server.com:/path-to-your-website.com/